### ISSUE TITLE
Issues linking with iOS8.4 armv7

### ISSUE THREAD

**Issue by Hobsie85** [davepeck/iOS-libarchive#15]
Hi There,

I'm having some serious issues trying to build a libarc.a that links correctly in another project with a bunch of these (not all listed but basically just any method I try to use):

```
Undefined symbols for architecture armv7:
"_archive_write_new", referenced from:
    _write_archive in ViewController.o
"_archive_write_set_format_pax_restricted", referenced from:
    _write_archive in ViewController.o
"_archive_write_finish", referenced from:
    _write_archive in ViewController.o
"_archive_write_open_filename", referenced from:
    _write_archive in ViewController.o
```

I can grab the libarc.a and headers that you've pre-built in the folder /build-for-iOS-4.3/ and it links fine in my own project, but the moment I try and build my own version of the library, either using the ./Build.sh or manually building and binding together using lipo I end up with a library that gives me linker errors for any methods I try to use in the library.

I'm currently using Xcode 6.4 (iPhoneOS 8.4).
I've checked that I'm linking with Libz correctly.

Running lipo -info on the libarc.a you supply gives me:
`armv6 armv7 i386 x86_64`

Running it on the library build I generate using ./build.sh gives me:
`armv7 armv7s i386 x86_64 arm64`

The build log is a bit long to paste in here but I'm not seeing any major issues (a few implicit casting warnings here and there in the libarchive source but that's about it).

Really at a loss as to why it's not linking correctly.

As an aside: I had to modify the ./Build.sh script to remove the "$SDK_VERSION" in order to build correctly (I'm not sure if they've changed the way you specify sdks version but iphoneos8.x doesn't exist for me while iphoneos does).

Any help with this is much appreciated as I'd really like to use this library (especially with 64bit support)

Cheers,
Hobsie

**Comment by Hobsie85** [comment]
I knew it would be something daft!

Looks like the headers/library you've pre-built have the libarchive methods as is while the source headers prefix all the methods with "tk_".

So I had grabbed the headers from build-for-iOS-4.3/ thinking they'd link with my own pre-build library. grabbing the headers directly out of the libarchive source directory (which have the tk_ prefixes) links fine now.

Can I suggest:
1. Adding a new pre-built package with the new headers or rebuild those packages with the new headers.
2. Update the build.sh as I don't think the syntax is correct anymore?

Cheers!
Hobsie

**Comment by davepeck** [comment]
Hi @Hobsie85 -- this repository hasn't been touched in years and is in desperate need of some love. Sorry you ran into that!

One of these days perhaps I'll get back to it... or some intrepid soul will take over and manage the project correctly.
